### ISSUE TITLE
New Feature Request to support Npcap

### ISSUE THREAD

**Issue by mikecotrone** [charonn0/RB-PCAP#2]
WinPcap development seized around 2013 using libpcap version 1.0.0. Npcap offers many new enhancements such as 802.11 capturing, libpcap 1.9.0, and can capture/inject loopback traffic. This project works fine only if you install Npcap using it's winpcap compatibility mode, but it would push the project forward if the Npcap sdk was used.

**Comment by charonn0** [comment]
I think the only thing we need to do is change the Windows DLL search path for the app so that the NPcap folder is searched before the WPcap folder.

i.e. install NPcap in non-compatibility mode then do this before using any PCAP methods or classes in your app:

```
  // in App.Open or similar 
  Soft Declare Function SetDllDirectoryW Lib "Kernel32" (PathName As WString) As Boolean
  Call SetDllDirectoryW(SpecialFolder.System.Child("Npcap").AbsolutePath)
```

**Comment by mikecotrone** [comment]
That worked perfectly thank you!
